### ISSUE TITLE
TimeLine component is missing in NPM package

### ISSUE THREAD

**Issue by dennismorello** [samboylett/react-epg#1]
Hi @samboylett,

first of all, thank you for your work. I am using your components in my React app but it seems that the version published on NPM lacks the TimeLine component. Could you please verify it and re-publish your package? In the source repository the TimeLine is present.

Thanks!

**Comment by samboylett** [comment]
Thanks for raising this, I've republished and bumped to version 0.1.1, can you check this solves the issue for you and close if it does?

**Comment by morellodev** [comment]
It seems to be ok now, we can close this issue.

Thanks!
